/*
 * tasks.h
 *
 *  Created on: May 6, 2026
 *      Author: LindUser
 */

#ifndef INC_TASKS_H_
#define INC_TASKS_H_

#include "cmsis_os.h"

/* Event flags for sensor_event_flags */
#define EVT_MOTION_DETECTED     (1 << 0)  /* ADXL_INT1 triggered */
#define EVT_ACQSTN_DONE        (1 << 1)  /* Settling complete */
#define EVT_UPLOAD_DONE        (1 << 2)  /* File uploaded */
#define EVT_CFG_CHECK          (1 << 3)  /* Config check timer */
#define EVT_FILE_READY         (1 << 4)  /* File closed, ready for upload */

/* Handles declared in freertos.c (generated by CubeMX) */
extern osThreadId_t sensor_taskHandle;
extern osThreadId_t modem_taskHandle;
extern osThreadId_t file_taskHandle;
extern osThreadId_t control_taskHandle;
extern osMutexId_t sd_mutexHandle;
extern osEventFlagsId_t sensor_event_flagsHandle;

/* Set by sensor_task after acquisition completes — read by control_task / CLI */
extern char latest_filename[32];

/* Task entry functions */
void StartSensorTask(void *argument);
void StartModemTask(void *argument);
void StartFileTask(void *argument);
void StartControlTask(void *argument);

/* RAM-based upload queue — replaces queue.txt to avoid FatFs write/read
 * race conditions. Producer: file_task. Consumer: modem_task. */
#define UPLOAD_QUEUE_SIZE 8

typedef struct {
    char files[UPLOAD_QUEUE_SIZE][32];
    volatile int head;
    volatile int tail;
    volatile int count;
} UploadQueue_t;

extern UploadQueue_t upload_queue;

/* Push a filename to the queue. Returns 1 on success, 0 if queue full. */
int upload_queue_push(const char* filename);

/* Pop (read + remove) the first filename from the queue.
 * Returns 0 on success, -1 if queue empty. */
int upload_queue_pop(char* buf, int size);

/* Peek at the first filename without removing it.
 * Returns 0 on success, -1 if queue empty. */
int upload_queue_peek(char* buf, int size);

/* Synchronization flag: set by modem_task during Modem_UploadFile,
 * checked by file_task to skip queue reads during upload (let queue accumulate
 * instead of opening a new file while SD mutex is held). */
extern volatile uint8_t upload_busy;

/* Abort flag — set by sdtest to force sensor task out of acquisition */
extern volatile uint8_t sdbg_abort_acq;

#endif /* INC_TASKS_H_ */