/*
 * tasks.h
 *
 *  Created on: May 6, 2026
 *      Author: LindUser
 */

#ifndef INC_TASKS_H_
#define INC_TASKS_H_

#include "cmsis_os.h"

/* Event flags for sensor_event_flags */
#define EVT_MOTION_DETECTED     (1 << 0)  /* ADXL_INT1 triggered */
#define EVT_ACQSTN_DONE        (1 << 1)  /* Settling complete */
#define EVT_UPLOAD_DONE        (1 << 2)  /* File uploaded */
#define EVT_CFG_CHECK          (1 << 3)  /* Config check timer */
#define EVT_FILE_READY         (1 << 4)  /* File closed, ready for upload */

/* Handles declared in freertos.c (generated by CubeMX) */
extern osThreadId_t sensor_taskHandle;
extern osThreadId_t modem_taskHandle;
extern osThreadId_t file_taskHandle;
extern osThreadId_t control_taskHandle;
extern osMessageQueueId_t sensor_queueHandle;
extern osMutexId_t sd_mutexHandle;
extern osEventFlagsId_t sensor_event_flagsHandle;

/* Task entry functions */
void StartSensorTask(void *argument);
void StartModemTask(void *argument);
void StartFileTask(void *argument);
void StartControlTask(void *argument);

/* Shared filename for upload pipeline */
extern char latest_filename[32];

/* RAM upload buffer — file_task reads CSV into this after closing.
 * modem_task uploads from here instead of re-reading SD (avoids brown-out data loss). */
extern uint8_t *upload_buf;
extern uint32_t upload_buf_size;

/* Abort flag — set by sdtest to force sensor task out of acquisition */
extern volatile uint8_t sdbg_abort_acq;

/* Data structure for the queue */
typedef struct {
    uint32_t timestamp_ms;
    float x_g;
    float y_g;
    float z_g;
    float voltage;
    float current;
    float power;
} SensorReading_t;

/* Compact binary format for RAM upload (28 bytes/sample, no SD dependency).
 * Backend converts BIN→CSV. Fits 1170 samples in 32KB. */
typedef struct __attribute__((packed)) {
    uint32_t timestamp_ms;
    float x_g;
    float y_g;
    float z_g;
    float voltage;
    float current;
    float power;
} BinarySample_t;

#define UPLOAD_BUF_CAPACITY  (32 * 1024)  /* 32KB = 1170 samples × 28 bytes */

#endif /* INC_TASKS_H_ */